services:
  db:
    image: postgres:17
    restart: always
    env_file:
      - backend/.env.${ENV:-development}
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    env_file:
      - backend/.env.${ENV:-development}
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${OSS_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${OSS_SECRET_KEY}
    ports:
      - "9000:9000"  # S3 API
      - "9001:9001"  # MinIO Console
    volumes:
      - ./data/minio:/data

  mailpit:
    image: axllent/mailpit:latest
    container_name: mailpit
    ports:
      - "8025:8025"   # Web UI
      - "1025:1025"   # SMTP
    restart: unless-stopped
    # Access the web UI at http://localhost:8025

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${BUILD_TARGET:-dev}
    depends_on:
      - db
      - minio
      - mailpit
    env_file:
      - backend/.env.${ENV:-development}
    environment:
      ENV: ${ENV:-development}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OSS_ACCESS_KEY: ${OSS_ACCESS_KEY}
      OSS_SECRET_KEY: ${OSS_SECRET_KEY}
      OSS_BUCKET: ${OSS_BUCKET}
      OSS_ENDPOINT: ${OSS_ENDPOINT}
      OSS_REGION: ${OSS_REGION}
      EMAIL_HOST: mailpit
      EMAIL_PORT: 1025
      EMAIL_FROM: noreply@example.com
    ports:
      - "8080:8080"
    volumes:
      - .:/app  # Only for development; see below
    working_dir: /app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  waha:
    image: devlikeapro/waha:latest
    container_name: waha
    ports:
      - "3000:3000"
    volumes:
      - ./data/waha-sessions:/sessions
    environment:
      - WAHA_SESSION_DIR=/sessions
    restart: unless-stopped

# ---
# Usage:
#   - For development: set ENV=development (default), BUILD_TARGET=dev
#   - For staging:     set ENV=staging,     BUILD_TARGET=staging
#   - For production:  set ENV=production,  BUILD_TARGET=prod
# Example:
#   set ENV=production
#   set BUILD_TARGET=prod
#   docker compose up --build
#
# For production/staging, remove or set the backend volumes to read-only:
#   volumes:
#     - .:/app:ro
#   Or remove the volume entirely for best security.
#
# Create these files for environment-specific variables:
#   backend/.env.development
#   backend/.env.staging
#   backend/.env.production

# ---
# Mailpit (axllent/mailpit) is available at http://localhost:8025 for email testing.
# Backend will send emails via SMTP to mailpit:1025.
# Configure EMAIL_HOST, EMAIL_PORT, and EMAIL_FROM in your .env files as needed.